#https://github.com/easingthemes/ssh-deploy
name: SSH Deploy to Ubuntu VPS

on:
  push:
    branches:  
      - main 

jobs:
  build-js-production:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: NPM Build
        run: |
          npm install
          npm run build
      - name: Put built assets in Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public	  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build-js-production ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Fetch built assets from Artifacts
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.0'
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: node_modules
        run: npm i		  
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.CONTABO_SSH_01232023_1}}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: "orders-crud.alenev.name"
          REMOTE_USER: "admin"
          SOURCE: ""
          TARGET: "/home/admin/web/orders-crud.alenev.name/public_html"
          EXCLUDE: "/.git/, /.github/, .env"
